CC = g++
CXXFLAGS = -std=c++11

project3: utils.cpp process.cpp os_basic.cpp os_schedule.cpp os_memory.cpp project3.cpp 
	$(CC) $(CXXFLAGS) utils.cpp process.cpp os_basic.cpp os_schedule.cpp os_memory.cpp project3.cpp -o project3
clean:
	rm -rf project3